export const NOTIFICATION_CHANNEL = {
  JOIN: "JOIN",
  NOTIFY: "NOTIFY",
};
export const PROJECT_CHANNEL = {
  JOIN_ROOM: "JOIN_ROOM",
  LEAVE_ROOM: "LEAVE_ROOM",

  ASSIGN_ADMIN: "ASSIGN_ADMIN",

  ADD_MEMBER: "ADD_MEMBER",

  JOIN_PROJECT: "JOIN_PROJECT",
  LEAVE_PROJECT: "LEAVE_PROJECT",

  ADD_TASK: "ADD_TASK",
  MOVE_TASK: "MOVE_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  DELETE_TASK: "DELETE_TASK",

  ADD_LIST: "ADD_LIST",
  MOVE_LIST: "MOVE_LIST",
  UPDATE_LIST: "UPDATE_LIST",
  DELETE_LIST: "DELETE_LIST",
};
